#General Settings
[General_Settings]
	#控制饱食度满时食用食物是否还计算营养值，默认false
	ignore_hunger = false

#Nutritions Settings
[Nutritions_Settings]
	#谷物营养值奖励节点设置
	grains_ranges = ["0-25:effect(minecraft:slowness,0)", "61-70:attribute(minecraft:generic.max_health,4.0)", "71-80:attribute(minecraft:generic.max_health,6.0),effect(minecraft:regeneration,0)", "81-100:attribute(minecraft:generic.max_health,6.0),attribute(minecraft:generic.attack_damage,1.0),effect(minecraft:regeneration,0)"]
	#水果营养值奖励节点设置
	fruits_ranges = ["0-25:effect(minecraft:mining_fatigue,0)", "61-70:attribute(minecraft:generic.max_health,2.0),attribute(minecraft:generic.attack_speed,0.05)", "71-80:attribute(minecraft:generic.max_health,4.0),attribute(minecraft:generic.attack_speed,0.1)", "81-100:attribute(minecraft:generic.max_health,6.0),attribute(minecraft:generic.attack_speed,0.2)"]
	#蔬菜营养值奖励节点设置
	vegetables_ranges = ["0-25:effect(minecraft:nausea,0)", "61-70:attribute(minecraft:generic.max_health,2.0),attribute(minecraft:generic.armor_toughness,2.0)", "71-80:attribute(minecraft:generic.max_health,2.0),attribute(minecraft:generic.armor_toughness,3.0)", "81-100:attribute(minecraft:generic.max_health,2.0),attribute(minecraft:generic.armor_toughness,4.0),effect(minecraft:haste,0)"]
	#蛋白质营养值奖励节点设置
	proteins_ranges = ["0-25:effect(minecraft:weakness,0)", "61-70:attribute(minecraft:generic.max_health,2.0),attribute(minecraft:generic.armor,1.0)", "71-80:attribute(minecraft:generic.max_health,4.0),attribute(minecraft:generic.armor,2.0)", "81-100:attribute(minecraft:generic.max_health,6.0),attribute(minecraft:generic.armor,4.0),effect(minecraft:resistance,0)"]
	#糖分营养值奖励节点设置
	sugars_ranges = ["51-60:effect(minecraft:speed,0)", "61-80:effect(minecraft:speed,1)", "81-100:effect(minecraft:speed,1),effect(minecraft:hunger,4)"]

#Initial Values Settings
[Initial_Values_Settings]
	#谷物营养值初始百分比，默认50%
	# Default: 0.5
	# Range: 0.0 ~ 1.0
	grains_initial = 0.5
	#水果营养值初始百分比，默认50%
	# Default: 0.5
	# Range: 0.0 ~ 1.0
	fruits_initial = 0.5
	#蔬菜营养值初始百分比，默认50%
	# Default: 0.5
	# Range: 0.0 ~ 1.0
	vegetables_initial = 0.5
	#蛋白质营养值初始百分比，默认50%
	# Default: 0.5
	# Range: 0.0 ~ 1.0
	proteins_initial = 0.5
	#糖分营养值初始百分比，默认50%
	# Default: 0.5
	# Range: 0.0 ~ 1.0
	sugars_initial = 0.5
